spring.application.name=Scout
spring.datasource.url=jdbc:mysql://localhost:3308/scout?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=scout_user
spring.datasource.password=scout1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true